### ISSUE TITLE
Failure to match regexes on chunk boundaries

### ISSUE THREAD

**Issue by dhasenan** [Jimmy02020/find-in#2]
The block size for `stream` is probably 64KB or so, so a regex match on the order of 16 bytes should always work, since it's a lot smaller than the block size.

However, whether it works depends greatly on the location in the file. Test case:

```javascript
const find = require("find-in")['default'];
const fs = require("fs");

let flen = 64 * 1024 * 3;
let rlen = 10;

let test = (i) => {
    let buf = Buffer.alloc(flen, ' ', 'utf8');
    buf.fill('B', i - 1, i + rlen + 1, 'utf8');
    buf.fill('A', i, i + rlen, 'utf8');
    fs.writeFileSync("test.txt", buf);
    find("test.txt", [/BA*B/], (err, report) => {
        let found = false;
        for (let r = 0; r < report.length; r++) {
            if (report[r].isFound) {
                found = true;
            }
        }
        if (!found) console.log(`${i}: missing`);
        if (i < flen - rlen - 10) {
            test(i + 1);
        }
    });
};

test(10);
```

In other words, for offsets in the file starting at 10 bytes and ending near 192KB, fill the file with ` `, then insert `BAAAAAAAAAAB` at the offset. Then search for it and report if it wasn't found.

That will churn for a while, then print:

```
65526: missing
65527: missing
65528: missing
65529: missing
65530: missing
65531: missing
65532: missing
65533: missing
65534: missing
65535: missing
65536: missing
```

I killed it at this point.

When the regex match overlaps the block boundary, it's not matched.

You can solve this by gluing subsequent pairs of blocks together. You'll still be able to match everything up to 64KB long. You'll be able to do this with a fixed amount of memory.

**Comment by Jimmy02020** [comment]
Hi @dhasenan  again
I changed the chunk size to 128 * 1024
and ran the same code
```
          if (!found) console.log(`${i}: missing`);
          else console.log(`${i}: found`);
```

Then test it
```
23559: found
23560: found
23561: found
23562: found
23563: found
23564: found
23565: found
23566: found
23567: found
```
passing the chunk size will fix this issue.

**Comment by dhasenan** [comment]
Passing in a larger chunk size reduces the number of chunk boundaries where I could miss a match. However, I don't know where in the file I might find a match, so I don't know what chunk size is right.

In order to fix this problem by specifying chunk sizes, I would need to:

1. Figure out how long a match I want to accept (say 1024 bytes)
2. Divide the length of the file by that twice number
3. Find two numbers whose least common multiple is greater than that ratio
4. Search with a chunk size based on the first number
5. Search again with a chunk size based on the second number

This ensures that any chunk boundary on the first pass is sufficiently far from a chunk boundary on the second pass that I can find every match. But then I have to search the whole file twice and do a bunch of awkward math.

Alternatively,  you could keep two chunks in memory, the current and the previous, join them together, and search through that union. So you read the first chunk, store it, read the second, and search through the first two as one string. Then you discard the first chunk, read the third, and search through both the second and third. And so forth.

**Comment by Jimmy02020** [comment]
This is definitely helping
I will work on it
This technique can help me also improving  [fmod ](https://github.com/Jimmy02020/fmod)
